package by.epam.tc.hr_system.controller.helper;

public enum CommandName {
	REGISTRATION, AUTHORIZATION, CHANGE_LOCAL, DELETE_VACANCY,
	CHANGE_RESPONCE_STATUS, CREATE_VACANCY, UPDATE_VACANCY, CREATE_RESUME, ADD_EDUCATION, SHOW_HR_VACANCY,
	SHOW_TOP_VACANCIES, SHOW_VACANCY, SHOW_RESPONCE, SHOW_RESPONCE_TO_VACANCY,
	SHOW_RESUME, RESPONCE_TO_VACANCY, LOG_OUT, SHOW_VACANCY_TO_UPDATE, 
	CHECK_AFFILIATION_VACANCY_TO_HR, UPDATE_PROFILE;

}
