package by.epam.tc.hr_system.controller.helper;

public enum CommandName {
	REGISTRATION, AUTHORIZATION, CHANGE_LOCAL, CREATE_VACANCY, CREATE_RESUME,
	SHOW_TOP_VACANCIES, SHOW_VACANCY, SHOW_RESPONCE, SHOW_RESUME, RESPONCE_TO_VACANCY, LOG_OUT;

}
